services:
  - type: web
    name: mobfix-backend
    runtime: node
    repo: https://github.com/manikanta-pasupuleti/MobFix.git
    branch: main
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: "production"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/services

  - type: web
    name: mobfix-frontend
    runtime: static
    repo: https://github.com/manikanta-pasupuleti/MobFix.git
    branch: main
    buildCommand: cd mobfix-frontend && chmod +x render-build.sh && ./render-build.sh
    staticPublishPath: dist/mobfix-frontend
    envVars:
      - key: API_URL
        sync: false
