export const SAMPLE_SERVICES = [
  // Android
  { _id: 'a1', serviceName: 'Android Screen Repair', description: 'Fix cracked or damaged screens for Samsung, Google Pixel, OnePlus and more.', price: 79, category: 'Screen', platform: 'Android', estimatedTime: '1-2 hours', warranty: '90 days', rating: 4.8, reviewCount: 234, isPopular: true, supportedBrands: ['Samsung', 'Google', 'OnePlus', 'Xiaomi'] },
  { _id: 'a2', serviceName: 'Android Battery Replacement', description: 'Restore your battery life with genuine replacement batteries.', price: 49, category: 'Battery', platform: 'Android', estimatedTime: '30-45 mins', warranty: '90 days', rating: 4.7, reviewCount: 189, isPopular: true, supportedBrands: ['Samsung', 'Google', 'OnePlus'] },
  { _id: 'a3', serviceName: 'Android Charging Port Fix', description: 'Repair or replace faulty USB-C charging ports.', price: 45, category: 'Charging', platform: 'Android', estimatedTime: '45 mins', warranty: '60 days', rating: 4.5, reviewCount: 156, supportedBrands: ['Samsung', 'Google', 'Motorola'] },
  { _id: 'a4', serviceName: 'Android Camera Repair', description: 'Fix blurry cameras, replace broken lenses and camera modules.', price: 65, category: 'Camera', platform: 'Android', estimatedTime: '1 hour', warranty: '90 days', rating: 4.4, reviewCount: 98, supportedBrands: ['Samsung', 'Google', 'OnePlus'] },
  { _id: 'a5', serviceName: 'Android Data Recovery', description: 'Recover lost photos, contacts, and files from Android devices.', price: 99, category: 'Data', platform: 'Android', estimatedTime: '2-4 hours', warranty: 'N/A', rating: 4.3, reviewCount: 67 },

  // iOS
  { _id: 'i1', serviceName: 'iPhone Screen Repair', description: 'Premium screen replacement for all iPhone models with True Tone support.', price: 129, category: 'Screen', platform: 'iOS', estimatedTime: '1 hour', warranty: '90 days', rating: 4.9, reviewCount: 456, isPopular: true, supportedBrands: ['iPhone 15', 'iPhone 14', 'iPhone 13', 'iPhone 12'] },
  { _id: 'i2', serviceName: 'iPhone Battery Replacement', description: 'Apple-certified battery replacement for optimal performance.', price: 69, category: 'Battery', platform: 'iOS', estimatedTime: '30 mins', warranty: '90 days', rating: 4.8, reviewCount: 312, isPopular: true, supportedBrands: ['iPhone 15', 'iPhone 14', 'iPhone 13'] },
  { _id: 'i3', serviceName: 'iPhone Charging Port Repair', description: 'Fix Lightning port issues and restore fast charging.', price: 59, category: 'Charging', platform: 'iOS', estimatedTime: '45 mins', warranty: '60 days', rating: 4.6, reviewCount: 178, supportedBrands: ['All iPhones'] },
  { _id: 'i4', serviceName: 'iPhone Camera Repair', description: 'Repair front/back cameras, fix focus issues and replace lenses.', price: 89, category: 'Camera', platform: 'iOS', estimatedTime: '1-2 hours', warranty: '90 days', rating: 4.5, reviewCount: 134, supportedBrands: ['iPhone 15', 'iPhone 14', 'iPhone 13'] },
  { _id: 'i5', serviceName: 'iPhone Water Damage Repair', description: 'Professional water damage assessment and component repair.', price: 149, category: 'Hardware', platform: 'iOS', estimatedTime: '24-48 hours', warranty: '30 days', rating: 4.2, reviewCount: 89 },
  { _id: 'i6', serviceName: 'Face ID Repair', description: 'Fix Face ID not working issues on iPhone X and later.', price: 179, category: 'Hardware', platform: 'iOS', estimatedTime: '2-3 hours', warranty: '90 days', rating: 4.4, reviewCount: 56 },

  // Tablet
  { _id: 't1', serviceName: 'iPad Screen Repair', description: 'Replace cracked iPad screens with original quality displays.', price: 149, category: 'Screen', platform: 'Tablet', estimatedTime: '2 hours', warranty: '90 days', rating: 4.7, reviewCount: 123, isPopular: true, supportedBrands: ['iPad Pro', 'iPad Air', 'iPad Mini'] },
  { _id: 't2', serviceName: 'iPad Battery Replacement', description: 'Restore your iPad battery capacity and performance.', price: 89, category: 'Battery', platform: 'Tablet', estimatedTime: '1-2 hours', warranty: '90 days', rating: 4.6, reviewCount: 87, supportedBrands: ['iPad Pro', 'iPad Air'] },
  { _id: 't3', serviceName: 'Samsung Tablet Repair', description: 'Screen and battery repairs for Galaxy Tab series.', price: 129, category: 'Screen', platform: 'Tablet', estimatedTime: '2 hours', warranty: '90 days', rating: 4.5, reviewCount: 65, supportedBrands: ['Galaxy Tab S9', 'Galaxy Tab S8', 'Galaxy Tab A'] },

  // Laptop
  { _id: 'l1', serviceName: 'Laptop Screen Replacement', description: 'Replace broken or cracked laptop displays.', price: 199, category: 'Screen', platform: 'Laptop', estimatedTime: '1-2 hours', warranty: '90 days', rating: 4.6, reviewCount: 145, isPopular: true, supportedBrands: ['MacBook', 'Dell', 'HP', 'Lenovo'] },
  { _id: 'l2', serviceName: 'Laptop Battery Replacement', description: 'Get your laptop running longer with a new battery.', price: 99, category: 'Battery', platform: 'Laptop', estimatedTime: '30-60 mins', warranty: '90 days', rating: 4.5, reviewCount: 112, supportedBrands: ['MacBook', 'Dell', 'HP'] },
  { _id: 'l3', serviceName: 'Laptop Keyboard Repair', description: 'Fix stuck, broken, or unresponsive keyboard keys.', price: 129, category: 'Hardware', platform: 'Laptop', estimatedTime: '1-2 hours', warranty: '60 days', rating: 4.4, reviewCount: 89, supportedBrands: ['MacBook', 'Dell', 'HP', 'Lenovo'] },
  { _id: 'l4', serviceName: 'SSD/RAM Upgrade', description: 'Boost your laptop performance with storage and memory upgrades.', price: 79, category: 'Hardware', platform: 'Laptop', estimatedTime: '30-60 mins', warranty: '90 days', rating: 4.7, reviewCount: 167, supportedBrands: ['Most Laptops'] },
  { _id: 'l5', serviceName: 'Virus Removal & Cleanup', description: 'Remove malware, viruses and optimize system performance.', price: 59, category: 'Software', platform: 'Laptop', estimatedTime: '1-2 hours', warranty: '30 days', rating: 4.3, reviewCount: 234 },

  // Website
  { _id: 'w1', serviceName: 'Website Bug Fixes', description: 'Fix errors, broken features, and performance issues on your website.', price: 99, category: 'Web', platform: 'Website', estimatedTime: '1-3 hours', warranty: '14 days', rating: 4.6, reviewCount: 78, isPopular: true },
  { _id: 'w2', serviceName: 'Website Speed Optimization', description: 'Make your website load faster with performance tuning.', price: 149, category: 'Web', platform: 'Website', estimatedTime: '2-4 hours', warranty: '30 days', rating: 4.7, reviewCount: 56 },
  { _id: 'w3', serviceName: 'WordPress Maintenance', description: 'Updates, backups, security patches for WordPress sites.', price: 79, category: 'Web', platform: 'Website', estimatedTime: '1-2 hours', warranty: '30 days', rating: 4.5, reviewCount: 89 },
  { _id: 'w4', serviceName: 'E-commerce Store Setup', description: 'Set up or fix your online store on Shopify, WooCommerce, etc.', price: 299, category: 'Web', platform: 'Website', estimatedTime: '4-8 hours', warranty: '30 days', rating: 4.8, reviewCount: 34 },
  { _id: 'w5', serviceName: 'Mobile App Debugging', description: 'Fix crashes, bugs and issues in iOS or Android apps.', price: 149, category: 'Software', platform: 'Website', estimatedTime: '2-6 hours', warranty: '14 days', rating: 4.4, reviewCount: 45 },

  // All Devices
  { _id: 'all1', serviceName: 'Free Device Diagnostics', description: 'Comprehensive device health check and repair recommendations.', price: 0, category: 'Other', platform: 'All', estimatedTime: '15-30 mins', warranty: 'N/A', rating: 4.9, reviewCount: 567, isPopular: true },
  { _id: 'all2', serviceName: 'Data Transfer Service', description: 'Transfer data between old and new devices safely.', price: 49, category: 'Data', platform: 'All', estimatedTime: '1-2 hours', warranty: 'N/A', rating: 4.6, reviewCount: 234 },
  { _id: 'all3', serviceName: 'Device Setup & Configuration', description: 'Complete setup of new devices with your accounts and preferences.', price: 39, category: 'Software', platform: 'All', estimatedTime: '30-60 mins', warranty: 'N/A', rating: 4.5, reviewCount: 178 }
];
